# Generated by Django 5.1.7 on 2025-05-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearnApp', '0004_quizquestion_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='lesson_pdfs/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='lesson_videos/'),
        ),
    ]
