# Generated by Django 5.1.7 on 2025-05-17 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eLearnApp', '0007_quiz_quizquestion_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='lesson',
        ),
    ]
