# Generated by Django 5.1.7 on 2025-05-17 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearnApp', '0009_quizattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='lesson',
        ),
        migrations.AddField(
            model_name='quizresult',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eLearnApp.quiz'),
            preserve_default=False,
        ),
    ]
