# Generated by Django 5.1.7 on 2025-05-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
