# Generated by Django 5.1.7 on 2025-05-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearn', '0003_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='course_images/default.jpg', null=True, upload_to='course_images/'),
        ),
    ]
